#define PJ_CONFIG_IPHONE 1
#undef PJ_IPHONE_OS_HAS_MULTITASKING_SUPPORT
#define PJ_IPHONE_OS_HAS_MULTITASKING_SUPPORT 0
#define PJ_ENABLE_EXTRA_CHECK 0
#define PJMEDIA_SRTP_HAS_AES_CM_256 0
#define PJ_HAS_IPV6 1
#include <pj/config_site_sample.h>
