//
//  ESConstants.h
//  ECSDK
//
//  Created by DerekHu on 2022/7/28.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

    
FOUNDATION_EXPORT NSString* const SETTINGS_APP_OBSERVER;
FOUNDATION_EXPORT NSString* const SETTINGS_OWN_WORKER_THREAD;
FOUNDATION_EXPORT NSString* const SETTINGS_APP_DIRECTORY;
FOUNDATION_EXPORT NSString* const SETTINGS_APP_LOG_LEVEL;
FOUNDATION_EXPORT NSString* const SETTINGS_APP_LOG_FILEPATH;
FOUNDATION_EXPORT NSString* const SETTINGS_SERVER_IP;
FOUNDATION_EXPORT NSString* const SETTINGS_SERVER_PORT;
FOUNDATION_EXPORT NSString* const SETTINGS_PROTOCOL;
FOUNDATION_EXPORT NSString* const SETTINGS_NAT_TYPE;
FOUNDATION_EXPORT NSString* const SETTINGS_USERNAME;
FOUNDATION_EXPORT NSString* const SETTINGS_PASSWORD;
FOUNDATION_EXPORT NSString* const SETTINGS_PROXY_SERVER_IP;
FOUNDATION_EXPORT NSString* const SETTINGS_PROXY_SERVER_PORT;
FOUNDATION_EXPORT NSString* const SETTINGS_KA_INTERVAL;
FOUNDATION_EXPORT NSString* const SETTINGS_KAD_DATA;
FOUNDATION_EXPORT NSString* const SETTINGS_USE_SRTP;
FOUNDATION_EXPORT NSString* const SETTINGS_SRTP_SECURE_SIGNALING;
FOUNDATION_EXPORT NSString* const SETTINGS_SPEECH_CODE;
FOUNDATION_EXPORT NSString* const SETTINGS_SPEECH_RATE;
FOUNDATION_EXPORT NSString* const SETTINGS_VAD;
FOUNDATION_EXPORT NSString* const SETTINGS_MEDIA_TRANSPORT_ADDRESS;
FOUNDATION_EXPORT NSString* const SETTINGS_MEDIA_TRANSPORT_PORT;
FOUNDATION_EXPORT NSString* const SETTINGS_NAT_ICE_ENABLE;
FOUNDATION_EXPORT NSString* const SETTINGS_NAT_TURN_ENABLE;
FOUNDATION_EXPORT NSString* const SETTINGS_NAT_REWRITE_USE;
FOUNDATION_EXPORT NSString* const SETTINGS_SRTP_USE;
FOUNDATION_EXPORT NSString* const SETTINGS_PAYLOADTYPES;
FOUNDATION_EXPORT NSString* const SETTINGS_AUTO_RECORD;
FOUNDATION_EXPORT NSString* const SETTINGS_SRTP_USE;
FOUNDATION_EXPORT NSString* const SETTINGS_ROUTER_NUMBER;
FOUNDATION_EXPORT NSString* const SETTINGS_CONTACT_REWRITE_USE;
FOUNDATION_EXPORT NSString* const SETTINGS_VIA_REWRITE_USE;
FOUNDATION_EXPORT NSString* const SETTINGS_LICENSE_PATH;

#define  SETTINGS_KA_INTERVAL_DEFAULT  15
FOUNDATION_EXPORT NSString* const SETTINGS_KAD_DATA_DEFAULT;

//FOUNDATION_EXPORT NSString* const SPEECH_CODE_OPUS;
//FOUNDATION_EXPORT NSString* const SPEECH_CODE_G711;
//FOUNDATION_EXPORT NSString* const SPEECH_CODE_G722;
//FOUNDATION_EXPORT NSString* const SPEECH_CODE_G726;
//FOUNDATION_EXPORT NSString* const SPEECH_CODE_G729;

#define  SPEECH_RATE_DEFAULT_OPUS  48000
#define  SPEECH_RATE_DEFAULT_G711  8000
#define  SPEECH_RATE_DEFAULT_G722  16000
#define  SPEECH_RATE_DEFAULT_G726  8000
#define  SPEECH_RATE_DEFAULT_G729  8000

#define  SRTP_DISABLE     0
#define  SRTP_OPTIONAL    1
#define  SRTP_MANDATORY   2

#define  SRTP_SIGNALING_NOTREQUIRED   0
#define  SRTP_SIGNALING_TLS           1
#define  SRTP_SIGNALING_ENDTOEND      2

FOUNDATION_EXPORT NSString* const PROTOCOL_UNSPECIFIED;
FOUNDATION_EXPORT NSString* const PROTOCOL_UDP;
FOUNDATION_EXPORT NSString* const PROTOCOL_TCP;
FOUNDATION_EXPORT NSString* const PROTOCOL_TLS;
FOUNDATION_EXPORT NSString* const PROTOCOL_SCTP;
FOUNDATION_EXPORT NSString* const PROTOCOL_LOOP;
FOUNDATION_EXPORT NSString* const PROTOCOL_LOOP_DGRAM;
FOUNDATION_EXPORT NSString* const PROTOCOL_START_OTHER;
FOUNDATION_EXPORT NSString* const PROTOCOL_IPV6;
FOUNDATION_EXPORT NSString* const PROTOCOL_UDP6;
FOUNDATION_EXPORT NSString* const PROTOCOL_TCP6;
FOUNDATION_EXPORT NSString* const PROTOCOL_TLS6;


FOUNDATION_EXPORT NSString* const DEFAULT_CONFIG_NAME;
#define  DEFAULT_SIP_PORT  10520

FOUNDATION_EXPORT NSString* const LOG_TAG;

FOUNDATION_EXPORT NSString* const CURRENT_CALL_ID;

//    #define  CALL_CODE_NONE = 0;
#define  CALL_CODE_RINGING  1
#define  CALL_CODE_ANSWER   2

#define  ES_INVALID_CALL_ID  -1
#define  ES_FAILED          0
#define  ES_SUCCESS         1
    

NS_ASSUME_NONNULL_END
